DELETE
FROM event;
TRUNCATE TABLE event RESTART IDENTITY;
-- ALTER TABLE event ALTER COLUMN id RESTART WITH 1;


DELETE
FROM transport;
TRUNCATE TABLE transport RESTART IDENTITY CASCADE;


DELETE
FROM passenger;
TRUNCATE TABLE passenger RESTART IDENTITY CASCADE;


DELETE
FROM address;
TRUNCATE TABLE address RESTART IDENTITY;


DELETE
FROM driver;
TRUNCATE TABLE driver RESTART IDENTITY CASCADE;
--
--
-- DELETE
-- FROM transport_driver;
-- TRUNCATE TABLE transport_driver RESTART IDENTITY;

-- DELETE FROM transport_driver;
--
-- UPDATE transport SET passenger_id = NULL WHERE passenger_id IS NOT NULL;
--
-- DELETE FROM passenger WHERE address_id IS NOT NULL;
--
-- TRUNCATE TABLE address RESTART IDENTITY;
--
-- TRUNCATE TABLE passenger RESTART IDENTITY;
--
-- TRUNCATE TABLE transport RESTART IDENTITY;
--
-- DELETE FROM transport_driver;
--
-- TRUNCATE TABLE driver RESTART IDENTITY;

-- DELETE FROM transport WHERE passenger_id IS NOT NULL;
--
-- DELETE FROM transport_driver;
-- DELETE FROM driver;
-- DELETE FROM transport;
-- DELETE FROM event;
-- DELETE FROM passenger;
-- DELETE FROM address;
--
-- TRUNCATE TABLE transport_driver RESTART IDENTITY;
-- TRUNCATE TABLE driver RESTART IDENTITY;
-- TRUNCATE TABLE transport RESTART IDENTITY;
-- TRUNCATE TABLE event RESTART IDENTITY;
-- TRUNCATE TABLE passenger RESTART IDENTITY;
-- TRUNCATE TABLE address RESTART IDENTITY;
