DELETE
FROM event;
TRUNCATE TABLE event RESTART IDENTITY;
-- ALTER TABLE event ALTER COLUMN id RESTART WITH 1;


DELETE
FROM transport;
TRUNCATE TABLE transport RESTART IDENTITY;


DELETE
FROM passenger;
TRUNCATE TABLE passenger RESTART IDENTITY;


DELETE
FROM address;
TRUNCATE TABLE address RESTART IDENTITY;


DELETE
FROM driver;
TRUNCATE TABLE driver RESTART IDENTITY;


DELETE
FROM transport_driver;
TRUNCATE TABLE transport_driver RESTART IDENTITY;
