DELETE FROM event;
TRUNCATE TABLE event RESTART IDENTITY;
-- ALTER TABLE event ALTER COLUMN id RESTART WITH 1;


DELETE FROM transport;
TRUNCATE TABLE transport RESTART IDENTITY;
-- ALTER TABLE transport ALTER COLUMN id RESTART WITH 1;

-- DELETE FROM passenger;
-- TRUNCATE TABLE passenger RESTART IDENTITY;
-- -- ALTER TABLE passenger ALTER COLUMN id RESTART WITH 1;